# Generated by Django 5.2 on 2026-09-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctoravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_fee',
        ),
    ]
